apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ui.fullname" . }}
  annotations:
    ingress.alb.yc.io/external-ipv4-address: "auto"
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: {{ template "ui.fullname" . }}
            port:
              number: {{ .Values.service.externalPort }}
