#################################################
# DO Community Playbooks: Docker
#################################################
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Add remote "ubuntu" user to "docker" group
      remote_user: ubuntu
      user:
        name: "ubuntu"
        group: "docker"
        append: yes
      tags:
        - docker

    - name: Download docker-compose 1.25.1-rc1
      get_url:
        url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: ~/docker-compose
        mode: '+x'

    - name: Check docker-compose exists
      stat: path=~/docker-compose
      register: docker_compose

    - name: Move docker-compose to /usr/local/bin/docker-compose
      command: mv ~/docker-compose /usr/local/bin/docker-compose
      when: docker_compose.stat.exists

    - name: Create a directory if it does not exist
      file:
        path: /srv/gitlab
        state: directory
        mode: '0755'

    - name: copy docker-compose to host
      remote_user: ubuntu
      copy:
        src: ../docker-compose.yml
        dest: /srv/gitlab/docker-compose.yml

    - name: Install gitlab
      shell:
        cmd: 'docker-compose up -d'
        chdir: /srv/gitlab